### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [kfogel/OneTime#32] opened 2021-03-31 03:36 UTC
Dear Karl,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by kfogel** [comment] 2022-09-10 05:33
Hi, @sergeevabc.  I think this is a duplicate of issue #30 -- please see my response there.

**Closed as completed by kfogel** 2022-09-10 05:33 UTC
